WIP: Keycloak chart
skyfjell/charts pull request #20
Opened 2022-09-06 19:18 UTC by npapapietro

2022-11-14 23:55 UTC, cameojokes requested changes

2022-11-14 23:55 UTC, cameojokes commented on charts/platform-auth/templates/_helpers.tpl
> +{{- define "platform-auth.helper.codecentricName" -}}
Make these like `platform-auth.helper.codecentric.name`

2022-11-14 23:55 UTC, cameojokes commented on charts/platform-auth/templates/_keycloak.tpl
> +#   existingSecret: "auth-pguser-keycloak"
What's this?

2022-11-14 23:55 UTC, cameojokes commented on charts/platform-auth/templates/_keycloak.tpl
> +#   username: "keycloak"
And this?

2022-11-14 23:55 UTC, cameojokes commented on charts/platform-auth/values.yaml
> +# keycloak:
Do we need these?

2022-11-15 15:20 UTC, npapapietro commented on charts/platform-auth/values.yaml
> +# keycloak:
yes

2022-11-16 23:27 UTC, merged