[platform-auth] Auth Refactor
skyfjell/charts pull request #63
Opened 2022-11-30 02:10 UTC by cameojokes

2022-11-30 15:24 UTC, npapapietro commented
Only real comment here is to add the labels on each resource from our `common` helm chart

2022-12-06 15:44 UTC, npapapietro requested changes

2022-12-16 21:16 UTC, cameojokes commented on charts/platform-auth/templates/components/proxy/namespace.yaml
> +  name: {{ list $component $ | include "skyfjell.common.format.component.namespace" }}
If we create it we want the labels yeah?

Kyverno policy now defaults istio injection on ns unless explicitly disabled.

2022-12-16 21:35 UTC, npapapietro approved these changes

2022-12-16 21:49 UTC, merged